apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openim-rpc-msg-to-message-api
  namespace: open-im
  labels:
    app.kubernetes.io/part-of: open-im
    environment: dev
    project: comeai
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openim-rpc-msg
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: comeai
          podSelector:
            matchLabels:
              app: message-api
      ports:
        - protocol: TCP
          port: 8080
